version: '3.7'
services:
  mysql:
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - /data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  app:
    build: .
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - mysql
    restart: always
