version: '3.7'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  app:
    build: .
    command: python main.py
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - mysql
    restart: always
